version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    environment:
      - REDIS_NODES=redis://redis1:6379,redis://redis2:6379  # Internal ports
      - DEBUG=true
    depends_on:
      - redis1
      - redis2

  redis1:
    image: redis:7
    container_name: redis1
    ports:
      - "7070:6379"  # Host 7070 -> Container 6379
    volumes:
      - redis1_data:/data
    command: redis-server --appendonly yes

  redis2:
    image: redis:7
    container_name: redis2
    ports:
      - "7071:6379"  # Host 7071 -> Container 6379
    volumes:
      - redis2_data:/data
    command: redis-server --appendonly yes

volumes:
  redis1_data:
  redis2_data: